App\Entity\Chat:
  attributes:
    id:
      groups: ['chat_read']
    createdAt:
      groups: ['chat_read']
    message:
      groups: ['chat_read', 'chat_write']
    user:
      groups: ['chat_read']
