App\Entity\User:
  attributes:
    id:
      groups: ['user_read', 'chat_read']
    email:
      groups: ['user_read']
    username:
      groups: ['user_read', 'chat_read']
    createdAt:
      groups: ['user_read']
    updatedAt:
      groups: ['user_read']
